ssttp-1176
hmrc/time-to-pay-arrangement pull request #14
Opened 2017-02-24 10:41 UTC by cavster

2017-02-24 11:28 UTC, Smudgey requested changes
Commit messages could also do with being updated / give more context for the changes

2017-02-24 11:28 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/JurisdictionCheckerConfig.scala
> +case class JurisdictionCheckerConfig(stotishPrefix:String , welsePrefix:String)
Typos - stotishPrefix, welsePrefix

2017-02-24 11:28 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
> +import uk.gov.hmrc.timetopay.arrangement.services.{DesTTPArrangementBuilder, _}
Optimize this import please

2017-02-24 11:28 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
> +    .getOrElse(throw new RuntimeException("LetterAndControl configuration required"))),JurisdictionCheckerService) {}
Double check this as discussed

2017-02-24 11:28 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/DesTTPArrangementBuilder.scala
> +class DesTTPArrangementBuilder(jurisdictionChecker: JurisdictionChecker) {
Anyone to make this implicit / not have to pass this through everywhere?

2017-02-24 11:28 UTC, Smudgey commented on project/MicroServiceBuild.scala
> +  //todo hook em back in
remove comment?

2017-02-24 14:26 UTC, Smudgey reviewed
Last things I can see

2017-02-24 14:26 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/DesArrangementServiceSpec.scala
> +import javax.inject.Inject
Can we remove this import?

2017-02-24 14:26 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilderSpec.scala
> +import javax.inject.Inject
Is this one still needed?

2017-02-24 14:26 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/TTPArrangementServiceSpec.scala
> +import javax.inject.Inject
Same again?

2017-02-24 14:37 UTC, cavster commented on test/uk/gov/hmrc/timetopay/arrangement/services/DesArrangementServiceSpec.scala
> +import javax.inject.Inject
We need this one ;)

2017-03-03 16:43 UTC, Smudgey commented on app/Module.scala
> +/*
This file could probably be deleted

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/TTPArrangementController.scala
> +import scala.concurrent.{ExecutionContext, Future}
It's not an issue, but wondering why these imports are just being moved around :P

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/TTPArrangementRepository.scala
> +import com.google.inject.{ImplementedBy, Singleton}
The imports and spacing in this file can be cleaned up

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceGlobal.scala
> +import uk.gov.hmrc.play.config.ServicesConfig
Imports and spacings can be cleaned up here again. Should also avoid adding imports in half way down the file

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceGlobal.scala
> +class  GuiceModule extends AbstractModule with ServicesConfig {
Double space after class

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
>   */
Imports + Spacings again

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
> +      getConfString("letterAndControl.salutation", "sfsds"),
We need to think of more appropriate second messages, 'sfsds' accidentally got left in

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
> +  val test = new LetterAndControlAndJurisdictionCHecker()
Rename from test

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/DesArrangementService.scala
> +        println("We have an error " + e)
println accidentally left in

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/DesArrangementService.scala
Imports + spacings

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
> +class LetterAndControlAndJurisdictionCHecker extends ServicesConfig {
Checker has a capitalised H

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/config/microserviceWiring.scala
> +      getConfString("jurisdictionChecker.scottish.postcode.prefix ", "sfsds"),
sfsds again

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/DesTTPArrangementBuilder.scala
> +class DesTTPArrangementBuilder @Inject()(l:LetterAndControlAndJurisdictionCHecker){
Perhaps rename val from 'l'

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/JurisdictionChecker.scala
Imports & spacing

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilder.scala
> +  println("bangsdfsdfdsfs")
remove println's

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilder.scala
> +import uk.gov.hmrc.timetopay.arrangement.config.{LetterAndControlConfig, LetterAndControlAndJurisdictionCHecker}
Optimise imports

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilder.scala
> +    println("I was called")
Remove println

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilder.scala
> +  println("bang")
Remove println

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/TTPArrangementService.scala
> +import uk.gov.hmrc.timetopay.arrangement.config.{DesArrangementApiService, ServiceRegistry}
Optimise imports

2017-03-03 16:43 UTC, Smudgey commented on app/uk/gov/hmrc/timetopay/arrangement/services/TTPArrangementService.scala
> +    println("requestrequest " + request)
Remove println

2017-03-03 16:43 UTC, Smudgey commented on conf/application.conf
> +        letterAndControl {
These should ideally be moved out of the microservice wrapper, but if this is needed to get it to work for now, go for it

2017-03-03 16:43 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/TTPArrangementControllerSpec.scala
Optimise imports

2017-03-03 16:43 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/DesTTPArrangementBuilderSpec.scala
> +import uk.gov.hmrc.play.test.{UnitSpec, WithFakeApplication}
Optimise imports

2017-03-03 16:43 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilderSpec.scala
> +  println("sadasdsad")
remove println's

2017-03-03 16:43 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/LetterAndControlBuilderSpec.scala
> +class LetterAndControlBuilderSpec extends UnitSpec with MockFactory   with ScalaFutures  {
extra spaces after MockFactory

2017-03-03 16:43 UTC, Smudgey commented on test/uk/gov/hmrc/timetopay/arrangement/services/TTPArrangementServiceSpec.scala
imports

2017-03-03 16:51 UTC, Smudgey approved these changes

2017-03-03 17:07 UTC, merged